# Generated by Django 5.0.4 on 2024-05-05 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '家事', 'verbose_name_plural': '家事'},
        ),
        migrations.AlterModelOptions(
            name='workprocess',
            options={'verbose_name': '家事プロセス', 'verbose_name_plural': '家事プロセス'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': '家事分類', 'verbose_name_plural': '家事分類'},
        ),
        migrations.AddField(
            model_name='work',
            name='processes',
            field=models.ManyToManyField(blank=True, related_name='works', to='houseworks.workprocess'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(max_length=200, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='work',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='work',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseworks.worktype', verbose_name='家事分類'),
        ),
        migrations.AlterField(
            model_name='workprocess',
            name='description',
            field=models.CharField(max_length=200, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='workprocess',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='workprocess',
            name='procedure_number',
            field=models.IntegerField(default=1, verbose_name='プロセス番号'),
        ),
        migrations.AlterField(
            model_name='workprocess',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='workprocess',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='workprocess',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseworks.work', verbose_name='家事'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='description',
            field=models.CharField(max_length=200, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
