# Generated by Django 5.0.4 on 2024-05-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0004_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '実行履歴', 'verbose_name_plural': '実行履歴'},
        ),
    ]
