# Generated by Django 5.0.4 on 2024-05-06 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0005_alter_history_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_regular',
            field=models.BooleanField(default=True, verbose_name='定期実行の有無'),
        ),
        migrations.CreateModel(
            name='WeekDaysOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=1, verbose_name='曜日')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseworks.work', verbose_name='家事')),
            ],
        ),
    ]
