# Generated by Django 5.0.4 on 2024-05-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0006_work_is_regular_weekdaysofwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekdaysofwork',
            options={'verbose_name': '実行日', 'verbose_name_plural': '実行日'},
        ),
        migrations.AlterField(
            model_name='weekdaysofwork',
            name='weekday',
            field=models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], default=0, verbose_name='曜日'),
        ),
    ]
