# Generated by Django 5.0.4 on 2024-05-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0008_rename_worktype_hashtag_alter_hashtag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='説明')),
                ('priority', models.IntegerField(choices=[(0, '緊急'), (1, '近いうちにやるべき'), (2, '余裕がある時にやる')], default=1)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '実行タイプ',
                'verbose_name_plural': '実行タイプ',
            },
        ),
        migrations.RemoveField(
            model_name='work',
            name='is_regular',
        ),
        migrations.AddField(
            model_name='work',
            name='interval_types',
            field=models.ManyToManyField(blank=True, related_name='works', to='houseworks.intervaltype'),
        ),
        migrations.DeleteModel(
            name='WeekDaysOfWork',
        ),
    ]
