# Generated by Django 5.0.4 on 2024-05-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0010_work_default_executor_alter_workprocess_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='interval_types',
        ),
        migrations.AddField(
            model_name='work',
            name='intervals',
            field=models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], default=0, verbose_name='実行日'),
        ),
    ]
