# Generated by Django 5.0.4 on 2024-05-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0012_remove_work_intervals_work_interval_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervaltype',
            name='priority',
        ),
    ]
