# Generated by Django 5.0.4 on 2024-05-19 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0013_remove_intervaltype_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='interval_types',
        ),
        migrations.RenameModel(
            old_name='IntervalType',
            new_name='Schedule',
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shcedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseworks.schedule')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseworks.work')),
            ],
        ),
    ]
