# Generated by Django 5.0.4 on 2024-05-19 04:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0014_remove_work_interval_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workschedule',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.CreateModel(
            name='WorkHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseworks.hashtag')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseworks.work')),
            ],
        ),
    ]
