# Generated by Django 5.0.4 on 2024-05-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0015_remove_work_hashtags_workschedule_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='next_execute_date',
            field=models.DateField(auto_now=True, verbose_name='次回予定日'),
        ),
    ]
