# Generated by Django 5.0.4 on 2024-05-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0016_work_next_execute_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'タスクの実行', 'verbose_name_plural': 'タスクの実行'},
        ),
        migrations.RenameField(
            model_name='workschedule',
            old_name='shcedule',
            new_name='schedule',
        ),
    ]
