# Generated by Django 5.0.4 on 2024-05-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseworks', '0017_alter_workschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='schedule',
            field=models.IntegerField(blank=True, choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日'), (8, '月に1回'), (16, '3カ月に1回'), (32, '半年に1回'), (64, '1年に回'), (128, '必要に応じて')]),
        ),
    ]
